[workspace]
members = ["arduboy", "core", "desktop"]
resolver = "3"

[workspace.package]
version = "0.2.0"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>"]
edition = "2024"

[profile.release]
codegen-units = 1
strip = true
lto = "fat"
